#!/bin/sh

echo "Formatting staged .cpp/.hpp files..."

# Get staged .cpp and .hpp files (not including deleted ones)
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp)$')

# If there are any such files, format them and add them back
if [ -n "$staged_files" ]; then
    echo "$staged_files" | xargs clang-format -i
    echo "$staged_files" | xargs git add
else
    echo "No staged .cpp or .hpp files to format."
fi