#!/bin/sh

echo "Formatting staged .cpp/.hpp/.cu/.cuh files..."

# Get staged files with relevant extensions (excluding deleted ones)
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp|cu|cuh)$')

# If there are any such files, format them and add them back
if [ -n "$staged_files" ]; then
    echo "$staged_files" | xargs clang-format -i
    echo "$staged_files" | xargs git add
else
    echo "No staged .cpp, .hpp, .cu, or .cuh files to format."
fi
